
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/tuna-os/corral/cmd"


)

var tests = []testing.InternalTest{

	{"TestResolveBackend_Registry", _test.TestResolveBackend_Registry},

	{"TestResolveBackend_NotFound", _test.TestResolveBackend_NotFound},

	{"TestRequireBackend", _test.TestRequireBackend},

	{"TestUniq", _test.TestUniq},

	{"TestAllVMNames_Empty", _test.TestAllVMNames_Empty},

	{"TestResolveNamespace_FromRegistry", _test.TestResolveNamespace_FromRegistry},

	{"TestResolveNamespace_Default", _test.TestResolveNamespace_Default},

	{"TestRequireOrPrompt_NoVMs", _test.TestRequireOrPrompt_NoVMs},

	{"TestRequireOrPrompt_EmptyArgs", _test.TestRequireOrPrompt_EmptyArgs},

	{"TestRequireOrPrompt_EmptyStringArg", _test.TestRequireOrPrompt_EmptyStringArg},

	{"TestRootCommand_HasExpectedSubcommands", _test.TestRootCommand_HasExpectedSubcommands},

	{"TestCreateCommand_Flags", _test.TestCreateCommand_Flags},

	{"TestCreateCommand_DefaultValues", _test.TestCreateCommand_DefaultValues},

	{"TestDeleteCommand_HasForceFlag", _test.TestDeleteCommand_HasForceFlag},

	{"TestSSHCommand_HasFlags", _test.TestSSHCommand_HasFlags},

	{"TestUniq_Empty", _test.TestUniq_Empty},

	{"TestUniq_Single", _test.TestUniq_Single},

	{"TestUniq_AllSame", _test.TestUniq_AllSame},

	{"TestResolveBackend_QemuExists", _test.TestResolveBackend_QemuExists},

	{"TestRequireBackend_WithRegistry", _test.TestRequireBackend_WithRegistry},

	{"TestConfigCommand_Exists", _test.TestConfigCommand_Exists},

	{"TestImagesCommand_Exists", _test.TestImagesCommand_Exists},

	{"TestPluginCommand_Exists", _test.TestPluginCommand_Exists},

	{"TestDoctorCommand_Exists", _test.TestDoctorCommand_Exists},

	{"TestWebCommand_Exists", _test.TestWebCommand_Exists},

	{"TestCreateCommand_ArgsValidation", _test.TestCreateCommand_ArgsValidation},

	{"TestSSHCommand_Use", _test.TestSSHCommand_Use},

	{"TestRootCommand_Use", _test.TestRootCommand_Use},

	{"TestStartCmd_NonexistentVM", _test.TestStartCmd_NonexistentVM},

	{"TestStopCmd_NonexistentVM", _test.TestStopCmd_NonexistentVM},

	{"TestInfoCmd_NonexistentVM", _test.TestInfoCmd_NonexistentVM},

	{"TestViewerCmd_NonexistentVM", _test.TestViewerCmd_NonexistentVM},

	{"TestDeleteCmd_NonexistentVM", _test.TestDeleteCmd_NonexistentVM},

	{"TestStartCmd_NoArgs", _test.TestStartCmd_NoArgs},

	{"TestLogsCmd_NonexistentVM", _test.TestLogsCmd_NonexistentVM},

	{"TestResolveSSHCredentials_SavesExplicitUsername", _test.TestResolveSSHCredentials_SavesExplicitUsername},

	{"TestResolveSSHCredentials_UsesRememberedUsernameWhenNoFlag", _test.TestResolveSSHCredentials_UsesRememberedUsernameWhenNoFlag},

	{"TestResolveSSHCredentials_FlagOverridesRemembered", _test.TestResolveSSHCredentials_FlagOverridesRemembered},

	{"TestResolveSSHCredentials_NoEntryFallsBackToEnvOrRoot", _test.TestResolveSSHCredentials_NoEntryFallsBackToEnvOrRoot},

	{"TestResolveSSHCredentials_FlagPasswordOverridesSaved", _test.TestResolveSSHCredentials_FlagPasswordOverridesSaved},

	{"TestSSHCmd_NonexistentVM", _test.TestSSHCmd_NonexistentVM},

	{"TestContains", _test.TestContains},

	{"TestKubevirtOnly_NonexistentVM", _test.TestKubevirtOnly_NonexistentVM},

	{"TestRunKubevirtCreate_InvalidImage", _test.TestRunKubevirtCreate_InvalidImage},

	{"TestRunKubevirtCreate_EmptyName", _test.TestRunKubevirtCreate_EmptyName},

	{"TestConfigCmd_Runnable", _test.TestConfigCmd_Runnable},

	{"TestRootCmd_PersistentPreRunE", _test.TestRootCmd_PersistentPreRunE},

	{"TestConfigCmd_RunE", _test.TestConfigCmd_RunE},

	{"TestImagesCmd_RunE", _test.TestImagesCmd_RunE},

	{"TestPluginCmd_Exists", _test.TestPluginCmd_Exists},

	{"TestRestartCmd_NonexistentVM", _test.TestRestartCmd_NonexistentVM},

	{"TestPauseCmd_NonexistentVM", _test.TestPauseCmd_NonexistentVM},

	{"TestMigrateCmd_NonexistentVM", _test.TestMigrateCmd_NonexistentVM},

	{"TestScaleCmd_NonexistentVM", _test.TestScaleCmd_NonexistentVM},

	{"TestSnapshotCmd_NonexistentVM", _test.TestSnapshotCmd_NonexistentVM},

	{"TestListCmd_Exists", _test.TestListCmd_Exists},

	{"TestDoctorCmd_Exists", _test.TestDoctorCmd_Exists},

	{"TestWebCmd_Exists", _test.TestWebCmd_Exists},

	{"TestNewCloneInput_SuggestsCloneSuffix", _test.TestNewCloneInput_SuggestsCloneSuffix},

	{"TestRunClone_RejectsNonKubevirtBackend", _test.TestRunClone_RejectsNonKubevirtBackend},

	{"TestRunClone_RejectsExistingTarget", _test.TestRunClone_RejectsExistingTarget},

	{"TestActionsListItems_IncludesClone", _test.TestActionsListItems_IncludesClone},

	{"TestCtToItem_ShowsPhaseAndPrivilege", _test.TestCtToItem_ShowsPhaseAndPrivilege},

	{"TestActionsListItemsCT_NoHypervisorConcepts", _test.TestActionsListItemsCT_NoHypervisorConcepts},

	{"TestNetworksAndAddNicCommands_Exist", _test.TestNetworksAndAddNicCommands_Exist},

	{"TestCreateCommand_LANServiceFlag", _test.TestCreateCommand_LANServiceFlag},

	{"TestLanServiceCmd_NonexistentVM", _test.TestLanServiceCmd_NonexistentVM},

	{"TestLanServiceCmd_AppliesForKnownVM", _test.TestLanServiceCmd_AppliesForKnownVM},

	{"TestAddNicCmd_Flags", _test.TestAddNicCmd_Flags},

	{"TestAddNicCmd_NonexistentVM", _test.TestAddNicCmd_NonexistentVM},

	{"TestNetworksCmd_NoNADs", _test.TestNetworksCmd_NoNADs},

	{"TestAttachLANBridge_ZeroNADsErrors", _test.TestAttachLANBridge_ZeroNADsErrors},

	{"TestAttachLANBridge_ExplicitNADPatchesVM", _test.TestAttachLANBridge_ExplicitNADPatchesVM},

	{"TestPerformCTAction_DispatchesToCTPackage", _test.TestPerformCTAction_DispatchesToCTPackage},

	{"TestCTCreate_PortsFlag", _test.TestCTCreate_PortsFlag},

	{"TestCtCmd_Subcommands", _test.TestCtCmd_Subcommands},

	{"TestCtCreateCmd_RequiresImage", _test.TestCtCreateCmd_RequiresImage},

	{"TestCtCreateCmd_Flags", _test.TestCtCreateCmd_Flags},

	{"TestCtCreateCmd_Success", _test.TestCtCreateCmd_Success},

	{"TestCtListCmd_Empty", _test.TestCtListCmd_Empty},

	{"TestCtCreateCmd_DevcontainerResolvesImage", _test.TestCtCreateCmd_DevcontainerResolvesImage},

	{"TestCtCreateCmd_DevcontainerMissingImageErrors", _test.TestCtCreateCmd_DevcontainerMissingImageErrors},

	{"TestCtCreateCmd_DevcontainerBuildWithoutImageErrors", _test.TestCtCreateCmd_DevcontainerBuildWithoutImageErrors},

	{"TestCtCreateCmd_DevcontainerExplicitImageOverridesJSON", _test.TestCtCreateCmd_DevcontainerExplicitImageOverridesJSON},

	{"TestCtCreateCmd_DevcontainerNotFoundErrors", _test.TestCtCreateCmd_DevcontainerNotFoundErrors},

	{"TestCtNamespaceOrDefault", _test.TestCtNamespaceOrDefault},

	{"TestPrintCatalog_EmptyHasHeaderColumns", _test.TestPrintCatalog_EmptyHasHeaderColumns},

	{"TestPrintCatalog_SingleImage", _test.TestPrintCatalog_SingleImage},

	{"TestPrintCatalog_MultipleImages", _test.TestPrintCatalog_MultipleImages},

	{"TestPrintCatalog_ContainerDisk", _test.TestPrintCatalog_ContainerDisk},

	{"TestPrintVMList_Empty", _test.TestPrintVMList_Empty},

	{"TestPrintVMList_SingleVM", _test.TestPrintVMList_SingleVM},

	{"TestPrintVMList_StoppedVM", _test.TestPrintVMList_StoppedVM},

	{"TestPrintVMList_MultiVM_Sorted", _test.TestPrintVMList_MultiVM_Sorted},

	{"TestPrintVMList_EmptyNamespace", _test.TestPrintVMList_EmptyNamespace},

	{"TestSearchCatalog", _test.TestSearchCatalog},

	{"TestPullTemplate", _test.TestPullTemplate},

	{"TestPullTemplate_UnknownImage", _test.TestPullTemplate_UnknownImage},

	{"TestTemplateName", _test.TestTemplateName},

	{"TestSearchBootcCatalog", _test.TestSearchBootcCatalog},

	{"TestSearchCatalogs_All", _test.TestSearchCatalogs_All},

	{"TestSearchCatalogs_OSOnly", _test.TestSearchCatalogs_OSOnly},

	{"TestSearchCatalogs_BootcOnly", _test.TestSearchCatalogs_BootcOnly},

	{"TestValidateImagesType", _test.TestValidateImagesType},

	{"TestCheckImportFormat", _test.TestCheckImportFormat},

	{"TestRunImport_URL", _test.TestRunImport_URL},

	{"TestRunImport_LocalFile", _test.TestRunImport_LocalFile},

	{"TestRunImport_MissingFile", _test.TestRunImport_MissingFile},

	{"TestRunImport_VMDKRejected", _test.TestRunImport_VMDKRejected},

	{"TestEphemeralSummary_RunningWithTimeLeft", _test.TestEphemeralSummary_RunningWithTimeLeft},

	{"TestEphemeralSummary_RunningPastExpiry", _test.TestEphemeralSummary_RunningPastExpiry},

	{"TestEphemeralSummary_InvalidExpiresAt", _test.TestEphemeralSummary_InvalidExpiresAt},

	{"TestEphemeralSummary_GCStopped", _test.TestEphemeralSummary_GCStopped},

	{"TestEphemeralSummary_UserStopped", _test.TestEphemeralSummary_UserStopped},

	{"TestPrintCatalog_ListsEachImage", _test.TestPrintCatalog_ListsEachImage},

	{"TestPrintCatalog_Empty", _test.TestPrintCatalog_Empty},

	{"TestPrintVMList_ShowsAllVMs", _test.TestPrintVMList_ShowsAllVMs},

	{"TestPrintVMList_SortsByName", _test.TestPrintVMList_SortsByName},

	{"TestPrintVMList_StatusIcons", _test.TestPrintVMList_StatusIcons},

	{"TestPrintVMList_MissingNamespaceAndNode", _test.TestPrintVMList_MissingNamespaceAndNode},

	{"TestPersistentPreRunE_InitializesRegistryStore", _test.TestPersistentPreRunE_InitializesRegistryStore},

	{"TestRootCmd_Metadata", _test.TestRootCmd_Metadata},

	{"TestTUI_ModelInitializationAndNavigation", _test.TestTUI_ModelInitializationAndNavigation},

	{"TestTUI_ActionApplicability", _test.TestTUI_ActionApplicability},

	{"TestTUI_RenderView", _test.TestTUI_RenderView},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/tuna-os/corral"
	testdeps.ImportPath = "github.com/tuna-os/corral/cmd"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

